# Generated by Django 5.0.6 on 2024-10-08 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('elonlar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ariza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_letter', models.TextField(verbose_name='Motivatsiya xati')),
                ('status', models.CharField(choices=[("ko'rib_chiqilmoqda", "Ko'rib chiqilmoqda"), ('rad_etildi', 'Rad etildi'), ('qabul_qilindi', 'Qabul qilindi')], default="ko'rib_chiqilmoqda", max_length=20, verbose_name='Ariza holati')),
                ('date_applied', models.DateTimeField(auto_now_add=True, verbose_name='Ariza topshirilgan sana')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elonlar.jobpost', verbose_name="Ish e'loni")),
            ],
            options={
                'verbose_name': 'Ariza',
                'verbose_name_plural': 'Arizalar',
            },
        ),
    ]
