# Generated by Django 5.1 on 2024-09-03 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_car_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='user',
        ),
    ]
