# Generated by Django 5.0.6 on 2024-10-08 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kompaniya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=200, verbose_name='Kompaniya nomi')),
                ('tavsif', models.TextField(verbose_name="Kompaniya haqida qisqacha ma'lumot")),
                ('joylashuv', models.CharField(max_length=200, verbose_name='Kompaniya joylashuvi')),
                ('veb_sayt', models.URLField(verbose_name='Kompaniyaning veb-sahifasi')),
                ('sanoat', models.CharField(max_length=100, verbose_name='Sanoat turi')),
                ('olchami', models.CharField(choices=[('kichik', 'Kichik'), ('orta', "O'rta"), ('katta', 'Katta')], max_length=10, verbose_name="Kompaniya o'lchami")),
                ('tashkil_etilgan_sana', models.DateField(verbose_name='Kompaniya tashkil etilgan sana')),
            ],
            options={
                'verbose_name': 'Kompaniya',
                'verbose_name_plural': 'Kompaniyalar',
            },
        ),
    ]
