# Generated by Django 5.1 on 2024-09-03 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_car_user'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
